natation_auth:
    resource: "@NatationAuthBundle/Controller/"
    type:     annotation
    prefix:   /

natation:
    resource: "@NatationBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
