# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    #providers:
    #    in_memory:
    #        memory: ~
    
    # see: https://auth0.com/blog/creating-your-first-symfony-app-and-adding-authentication/
    encoders:
        NatationAuthBundle\Entity\Utilisateur: 
            algorithm: bcrypt
            cost: 15
            
    providers:
        database_users:
            entity: { class: NatationAuthBundle:Utilisateur, property: mail }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

            guard:
                authenticators:
                    - form_login_authenticator
            logout:
                path: /logout
                target: /